name: huerto_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/app_logo.png
    - lib/images/icons/trophy_35dp_E3E3E3_FILL0_wght400_GRAD0_opsz40.png
    # - lib/data/achievements_data.json